"""Backward-compatibility gate (release blocker for the Nostr/shared-context work).

Pins observable behaviour of AgentM2M 0.2.0 that the new collaboration and
observability planes must not change: the MCP tool surface, the host-mode
binding payload, the exact prompts (footprint-bounded prompting), version
stamps of a workspace saved by 0.2.0, and phi for every template. Fixtures
under fixtures/ were generated by 0.2.0 itself.
"""
from __future__ import annotations

import json
import re
import shutil
from pathlib import Path

import pytest

from agentm2m.engine.executor import PendingBinding
from agentm2m.engine.trace import TraceLink
from agentm2m.llm.mock_backend import MockBackend
from agentm2m.workspace import Workspace, list_templates
from tests._support import fill_all

FIXTURES = Path(__file__).parent / "fixtures"
REPO = Path(__file__).resolve().parents[2]

V0_2_TOOLS = {
    "team_init", "team_status", "team_validate", "model_show", "model_edit", "impact",
    "run", "next_bindings", "submit_binding", "trace_query", "team_evolve", "acceptance",
}


def _server_tools() -> set[str]:
    src = (REPO / "src/agentm2m/mcp_server.py").read_text()
    return set(re.findall(r"@mcp\.tool\(\)\ndef (\w+)\(", src))


def test_v0_2_mcp_tools_still_exposed():
    assert V0_2_TOOLS <= _server_tools()


def test_pending_binding_payload_keys_preserved():
    pb = PendingBinding(handoff="H", rule="R", target_key="R::t::m", binding="b", prompt="p", fp_digest="d")
    assert {"handoff", "rule", "target_key", "binding", "prompt", "attempts", "kind", "footprint_version"} <= set(pb.to_dict())


def test_trace_link_v1_roundtrip():
    state = json.loads((FIXTURES / "devteam_state_v1.json").read_text())
    for payload in state["traces"].values():
        for d in payload["links"]:
            again = TraceLink.from_dict(d).to_dict()
            # `footprints` is a debug copy that 0.2.0 already re-serializes
            # lossily on reload (dict -> key list); everything else is exact.
            for k, v in d.items():
                if k != "footprints":
                    assert again[k] == v


@pytest.fixture
def v1_workspace(tmp_path: Path) -> Workspace:
    ws = Workspace(tmp_path, backend="host", max_resamples=3)
    ws.init("devteam")
    shutil.copy(FIXTURES / "devteam_state_v1.json", ws.state_path)
    return Workspace(tmp_path, backend="host", max_resamples=3)


def test_v1_state_loads_with_every_stamp_fresh(v1_workspace: Workspace):
    acc = v1_workspace.acceptance()
    assert acc["phi"] is True, acc["open"]
    assert v1_workspace.run()["pending"] == 0


def test_prompts_are_byte_identical_to_v0_2(tmp_path: Path):
    golden = json.loads((FIXTURES / "devteam_prompts_v0_2.json").read_text())
    ws = Workspace(tmp_path, backend="host", max_resamples=3)
    ws.init("devteam")
    seen: dict[str, dict] = {}

    def answer(b: dict) -> str:
        seen[f"{b['target_key']}|{b['binding']}"] = {"prompt": b["prompt"], "footprint_version": b["footprint_version"]}
        from tests._support import good_value

        return good_value(b)

    fill_all(ws, answer)
    assert seen == golden


# phi each template reaches with the deterministic mock backend in 0.2.0
# (the mock's generic answers fail one incident validator: an escalation).
MOCK_PHI = {"devteam": True, "research": True, "incident": False}


@pytest.mark.parametrize("template", list_templates())
def test_every_template_mock_run_unchanged(tmp_path: Path, template: str):
    ws = Workspace(tmp_path, llm=MockBackend(), max_resamples=3)
    ws.init(template)
    ws.run()
    assert ws.validate()["ok"]
    assert ws.acceptance()["phi"] is MOCK_PHI[template]
